default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     '192.168.99.100'
  port:     '5432'
  username: 'postgres'
  database: 'question_and_answer_development'

test:
  <<: *default
  host:     '192.168.99.100'
  port:     '5432'
  username: 'postgres'
  database: 'question_and_answer_test'

production:
  url: <%= ENV['DATABASE_URL'] %>
